[package]
name = "crownotify"
version = "0.1.0"
edition.workspace = true
authors.workspace = true
rust-version.workspace = true
license.workspace = true
repository.workspace = true
homepage.workspace = true
description = "Notification daemon for CrownOS."
keywords = ["crownos", "wayland", "notifications", "dbus", "layershell"]
categories = ["gui", "os::linux-apis"]
readme = "README.md"
documentation = "https://docs.rs/crownotify"

[dependencies]
crownshell = { workspace = true }

anyhow = { workspace = true }
log = { workspace = true }
env_logger = { workspace = true }

vello = { workspace = true }
parley = { workspace = true }
calloop = "0.13"

smol = "2.0.2"
zbus = "5.16.0"
