[package]
name = "crownpositor-config"
version = "0.1.0"
edition.workspace = true
rust-version.workspace = true
license.workspace = true
authors.workspace = true
repository.workspace = true
homepage.workspace = true
description = "Compositor configuration types for CrownOS."
keywords = ["crownos", "wayland", "compositor", "config"]
categories = ["config", "os::linux-apis"]
readme = "README.md"
documentation = "https://docs.rs/crownpositor-config"

[dependencies]
crownos-config = { workspace = true }
regex = "1.13.1"
tracing = { workspace = true }
